hsp =0;
global.avatar_vsp = 0;
walksp = 4;
grv = 0.4;
alarm[0]= 20;
shot = true;
invincible = false;
timer = 0;
duration = 60;
spriteState = 0
respawn = false;
player_respawn_timer = 0;
player_respawn_interval = 180;
show = true;